# Generated by Django 5.0.1 on 2024-01-26 07:43

import attendanceManagement.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10)),
                ('age', models.IntegerField()),
                ('contact_address', models.CharField(max_length=200)),
                ('emp_email', models.EmailField(max_length=254)),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.department')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Details',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('present', models.BooleanField()),
                ('in_time', models.TimeField(null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Face_Data',
            fields=[
                ('face_id', models.AutoField(primary_key=True, serialize=False)),
                ('face', models.ImageField(blank=True, null=True, upload_to='')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint_Data',
            fields=[
                ('fp_id', models.AutoField(primary_key=True, serialize=False)),
                ('fp', models.ImageField(blank=True, null=True, upload_to=attendanceManagement.models.upload_fp_to)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Details',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('fp_status', models.BooleanField(default=False)),
                ('pin_status', models.BooleanField(default=False)),
                ('lock_status', models.BooleanField(default=False)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Pin_Data',
            fields=[
                ('pin_id', models.AutoField(primary_key=True, serialize=False)),
                ('pin_code', models.IntegerField(null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('MAC', models.CharField(max_length=200, null=True)),
                ('lock_status', models.BooleanField(default=False)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.department')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.topic')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.topic'),
        ),
    ]
